services:
  # Back End
  backend:
    build: 
      context: ./backend
    ports:
      - 8080:8080
    volumes:
      - '/usr/src/app'
    
  # Front End
  frontend:
    build:
      context: ./frontend
    ports:
      - 4200:4200
    volumes:
      - './frontend:/app/client'
      - '/app/client/node_modules'

  # Database
  database:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: