spring:
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    username: postgres
    password: asbptemplate
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev

# Additional configurations
server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
